### ISSUE TITLE
thermo_update_temps.php

### ISSUE THREAD

**Issue by Lerrissirrel** [ThermoMan/Thermostat-Tracking#63]
Well, I'm looking to get back into working on some things and decided to grab all the latest updates.

I noticed this php script was changed to require a time parameter.  It looks like this change intends you to use the kshell script as opposed to running the php script directly.  Is that right?  If so I can update the documentation.

**Comment by ThermoMan** [comment]
Do you mean the script and pho that fetches the status each minute?  If so then yes that is the intention and thanks!
I had run into the case where the OS platform, the DB platform, and the web-server each had their own (and different) ideas about what time it was.  So since the cron timer was OS based that time stamp carries through on certain operations.


--
In the mean time I've actually gotten a job as a web developer (and think this project played at least a small part in that) and have learned jQuery.  Although I still like my original idea to keep the web code as lightweight as possible I have a new respect for how fast jQuery runs and the next major revision may start with it.

**Comment by Lerrissirrel** [comment]
Actually, it's the script that runs every half hour.  Then, of course, I forgot to change the time zone in config.ksh so I thought my updates had stopped working 3 hours ago (I'm on the east coast).  I'll look for a way to make this a common config item.

Congrats on the new job.  I've looked at jQuery a bit myself although I never tried anything with it.  It looked like it could make a whole bunch of things a lot easier.

**Comment by ThermoMan** [comment]
All good now?

In other news all the manual ajax I wrote is now updated with jQuery and I'm using bootstrap for the UI.  New code update coming soon.
